#Category_gen extension
category_dir: trips
category_title_prefix: "Trips &raquo; "

#Files to exclude
exclude: Rakefile

paginate: 5 
safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      false
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:categories/:title.html

maruku:
  use_tex:    false
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

