task :default => [:"deploy:dev"]

desc "deletes _site"
task :delete do
	puts "deleting _site"
	system('rm -r _site')
	puts "deleting _site complete"
end

desc "build _site"
namespace :build do
	desc "build and deploy dev"
	task :dev => [:delete] do
		puts "building _site"
		system('ejekyll --server 9000 --auto')
	end

	desc "build pro"
	task :prod => [:delete] do
		puts "building _site"
		puts "building production _site"
		system('ejekyll')
		puts "building _site complete"
	end

end

desc "rsync _site"
task :rsync => :"build:prod" do
	system('rsync -rz --delete _site/ throughnothing@throughnothing.com:/var/www/blog.throughnothing.com')
end

desc "deploy the application"
namespace :deploy do
	desc "builds the development _site"
	task :dev => [:"build:dev"] do
		puts "dev site deployed"
	end

	desc "builds the production _site and deploys it"
	task :prod => [:rsync] do
		puts "pro site deployed"
	end
end
