task :default => [:"deploy:dev"]

desc "deletes _site"
task :delete do
	puts "deleting _site"
	#system('rm -r _site')
	puts "deleting _site complete"
end

desc "build _site"
namespace :build do
	desc "build and deploy dev"
	task :dev => [:delete] do
		puts "building _site"
		system('jekyll --server 9000 --auto')
	end

	desc "build pro"
	task :prod => [:delete] do
		puts "building _site"
		puts "building production _site"
		system('jekyll')
		puts "building _site complete"
	end

end

desc "rsync _site"
task :rsync => :"build:prod" do
    # Old system to slice
	#system('rsync -rz --delete _site/ throughnothing@throughnothing.com:/var/www/throughnothing.com')
	system('mkdir -p /tmp/s3fs-throughnothing.com')
	system('s3fs www.throughnothing.com /tmp/s3fs-throughnothing.com -o use_rrs=1 -o default_acl=public-read')
	system('jekyll --no-auto . /tmp/s3fs-throughnothing.com')
    system('fusermount -u /tmp/s3fs-throughnothing.com')
    system('rm -rf /mp/s3fs-throughnothing.com')
end

desc "deploy the application"
namespace :deploy do
	desc "builds the development _site"
	task :dev => [:"build:dev"] do
		puts "dev site deployed"
	end

	desc "builds the production _site and deploys it"
	task :prod => [:rsync] do
		puts "pro site deployed"
	end
end

desc "generate static elements for the site"
namespace :gen do
	desc "generate _js/photos_json.js file for flickr"
	task :photos_json do
		puts "generating photos_json.js"
		system('./_scripts/flickr_generator.py travel_photos_json > _js/photos_json.js')
		puts "generating photos_json.js complete"
	end
	desc "generate _js/photos_json.js file for flickr"
	task :photos_kml_date, :date do |t, args|
		date = args[:date]
		puts "generating kml/#{date}-photos.kml"
		system("./_scripts/flickr_generator.py photos_kml_date #{date} > kml/#{date}-photos.kml")
		puts "generating kml/#{date}-photos.kml complete"
	end
end
