name: Build and deploy to github pages
on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.8.2'
    steps:
      - name: Checkout dev
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Build with 11ty
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          cname: throughnothing.com
          publish_dir: _site
